### ISSUE TITLE
New Recipes: SPSS Statistics 28 (Node & Floating)

### ISSUE THREAD

**Issue by grahampugh** [eth-its/autopkg-mac-recipes-yaml#27]
SPSS 28 has been requested.

**Comment by grahampugh** [comment]
SPSS 28 recipes pushed.
SPSS 27 recipes moved to `_Deprecated Recipes` folder (except the uninstall recipes).

**Comment by grahampugh** [comment]
**Problem:**
The app is unpackaged into `/Applications/IBM SPSS Statistics` (no major version in the folder name). I think this will have to be corrected in the pkg recipe so that we can continue to allow multiple versions to be installed.

**Comment by katidzehnder** [comment]
- Uninstaller still missing
- Version 28 does show uninstallers of version 27
- 'Auto-update SPSS 27 Node License to 2021' does run as soon as node 28 is activated.

**Comment by grahampugh** [comment]
- Uninstallers are in place.
- `installed` groups now look at major version.
- A policy is still required to update SPSS 27 licenses to 2022.
